[package]
name = "musha-boot"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
r-efi = "=5.3.0"
musha-framebuffer = { path = "../framebuffer" }

musha-memory = { path = "../memory" }

musha-platform = { path = "../platform" }

[features]
qemu-debug = []
fault-ud = ["qemu-debug"]
fault-gp = ["qemu-debug"]
fault-df = ["qemu-debug"]
fault-pf = ["qemu-debug"]
fault-ro = ["qemu-debug"]
fault-nx = ["qemu-debug"]
fault-guard = ["qemu-debug"]
